
#Wire Settings
[wires]

	#Networking Cable Cable Stettings
	[wires.cc]
		#Networking Cable Cable Max Length
		#Range: 4 ~ 256
		ccMaxLen = 16

	#Logic Cable Cable Stettings
	[wires.id]
		#Logic Cable Cable Max Length
		#Range: 4 ~ 256
		idMaxLen = 16

